INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Містечко', 'Махнівка', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Махнівка', '49.7202412794062', '28.67118013641928', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Медведівка', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Медведівка', '49.74731078605156', '28.664061956324876', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Жежелів', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Жежелів', '49.796089617641904', '28.64785858328284', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Глухівці', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Глухівці', '49.77623388884417', '28.727151916115872', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Пляхова', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Пляхова', '49.74089169906793', '28.734225039065272', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Пиковець', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Пиковець', '49.68059206783239', '28.750969573251815', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Пустоха', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Пустоха', '49.67872401146283', '28.723398831558335', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Рубанка', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Рубанка', '49.66097389630644', '28.78734563067631', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Куманівка', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Куманівка', '49.650560752403834', '28.703064696435007', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Туча', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Туча', '49.637900047886774', '28.65924756983949', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Мшанець', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Мшанець', '49.684450400605975', '28.67178360828685', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Вуйна', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Перемога', '49.665898260626', '28.64172877542084', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Марківці', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Марківці', '49.69038866293102', '28.63857534165621', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Бродецьке', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Бродецьке', '49.75774257037466', '28.62984107423445', '1', 'ЦДІАК Ф49. О3. С212', 'ЦДІАК', '49', '3', '212', NULL, NULL, '1795', '273', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Село', 'Юрівка', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Юрівка', '49.75181271228285', '28.467416754635245', '1', 'ЦДІАК Ф11.О1. С54', 'ЦДІАК', '11', '1', '54', NULL, NULL, '1769', '650', '434', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Село', 'Осична', 'Вінницька обл.', 'Хмільницький р-н', 'Уланівська ОТГ', 'Село', 'Осична', '49.712581407787965', '28.44033866187944', '1', 'ЦДІАК Ф11.О1. С54', 'ЦДІАК', '11', '1', '54', NULL, NULL, '1769', '650', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Село', 'Богудзенька', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Листопадівка', '49.757153312172484', '28.41906634605606', '1', 'ЦДІАК Ф11.О1. С54', 'ЦДІАК', '11', '1', '54', NULL, NULL, '1769', '650', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Село', 'Великі Низгірці', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Великі Низгірці', '49.89090540561745', '28.695046691125054', '1', 'ЦДІАК Ф2.О1.С71', 'ЦДІАК', '2', '1', '71', NULL, NULL, '1771', NULL, '573', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Село', 'Великі Низгірці', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Великі Низгірці', '49.89090540561745', '28.695046691125054', '1', 'ЦДІАК Ф2.О1.С71', 'ЦДІАК', '2', '1', '71', NULL, NULL, '1771', NULL, '462', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Містечко', 'Махнівка', 'Вінницька обл.', 'Хмільницький р-н', 'Махнівська ОТГ', 'Село', 'Махнівка', '49.7202412794062', '28.67118013641928', '1', 'ЦДІАК Ф2. О1. С57', 'ЦДІАК', '2', '1', '57', NULL, NULL, '1773', NULL, '1025', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Махнівський ключ', 'Село', 'Глухівці', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Глухівці', '49.77623388884417', '28.727151916115872', '1', 'ЦДІАК Ф2. О1. С57', 'ЦДІАК', '2', '1', '57', NULL, NULL, '1773', NULL, '1029', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Кашперівський ключ', 'Cело', 'Кашперівка', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Кашперівка', '49.85843280342227', '28.891380345070793', '1', 'ЦДІАЛ Ф.134 О.1 С.1183', 'ЦДІАЛ', '134', '1', '1183', NULL, NULL, '1774', '8', '2', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Cело', 'Закиянка', NULL, NULL, 'Глуховецька ОТГ', 'Село', 'Кашперівка', '49.85843280342227', '28.891380345070793', '1', 'ЦДІАЛ Ф.134 О.1 С.1183', 'ЦДІАЛ', '134', '1', '1183', NULL, NULL, '1774', '8', '3', NULL, NULL, 'Закиянка зараз частина с.Кашперівка', 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', NULL, 'Cело', 'Пʼятигірка', 'Житомирська обл.', 'Бердичівський р-н', 'Андрушівська ОТГ', 'Село', 'Мала П`ятигірка', '49.8659836230058', '28.930211230814656', '1', 'ЦДІАЛ Ф.134 О.1 С.1183', 'ЦДІАЛ', '134', '1', '1183', NULL, NULL, '1774', '8', '3', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', 'Житомирський повіт', 'Кашперівський ключ', 'Cело', 'Бровки', 'Житомирська обл.', 'Бердичівський р-н', 'Андрушівська ОТГ', 'Село', 'Бровки Другі', '49.90035419878581', '28.890654416577004', '1', 'ЦДІАЛ Ф.134 О.1 С.1202', 'ЦДІАЛ', '134', '1', '1202', NULL, NULL, '1785', '4', '1', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', 'Махнівський повіт', 'Білопільський ключ', 'Cело', 'Верболози', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Верболози', '49.79925499958682', '28.853594203073772', '1', 'ЦДІАЛ Ф.134 О.1 С.1224', 'ЦДІАЛ', '134', '1', '1224', NULL, '1820–1824', NULL, '39', '5', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', 'Житомирський повіт', 'Білопільський ключ', 'Село', 'Малі Гадомці', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Малі Гадомці', '49.874188190491836', '28.82860623202032', '1', 'ЦДІАЛ Ф.134 О.1 С.1201', 'ЦДІАЛ', '134', '1', '1201', NULL, NULL, '1784', '6', '1', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', 'Махнівський повіт', 'Білопільський ключ', 'Село', 'Янківці (Іванківці)', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Іванківці', '49.75520906173887', '28.851146130770434', '1', 'ЦДІАЛ Ф.134 О.1 С.1229', 'ЦДІАЛ', '134', '1', '1229', NULL, NULL, '1831', '2', '1', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', NULL, NULL, 'Село', 'Сингаївка', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Сингаївка', '49.869424672767025', '28.773496602136518', '1', 'ЦДІАЛ Ф.134 О.1 С.1210', 'ЦДІАЛ', '134', '1', '1210', NULL, NULL, '1795', '8', '1', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', NULL, NULL, 'Село', 'Сингаївка', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Сингаївка', '49.869424672767025', '28.773496602136518', '1', 'ЦДІАЛ Ф.134 О.1 С.1211', 'ЦДІАЛ', '134', '1', '1211', NULL, '1795-1796', NULL, '11', '1', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', 'Махнівський повіт', 'Закутинецький ключ', 'Село', 'Закутинці', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Закутинці', '49.87114445008695', '28.805248611369652', '1', 'ЦДІАЛ Ф.134 О.1 С.1226', 'ЦДІАЛ', '134', '1', '1226', NULL, NULL, '1822', '16', '2', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київська губернія', 'Махнівський повіт', 'Білопільський ключ', 'Містечко', 'Білопілля', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Білопілля', '49.844930337728755', '28.869368844803198', '1', 'ЦДІАЛ Ф.134 О.1 С.1226', 'ЦДІАЛ', '134', '1', '1226', NULL, NULL, '1822', NULL, '5', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Місто', 'Ширмівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ширмівка', '49.56122492595613', '29.09840937926036', '1', 'AGAD 1/354/0/25/4239', NULL, NULL, NULL, NULL, NULL, NULL, '1733', '7', '3', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Ліщинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ліщинці', '49.56599569863322', '29.174227233627267', '1', 'AGAD 1/354/0/25/4239', NULL, NULL, NULL, NULL, NULL, NULL, '1733', '7', '5', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Смаржинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Смаржинці', '49.535510565016175', '29.145801900755792', '1', 'AGAD 1/354/0/25/4239', NULL, NULL, NULL, NULL, NULL, NULL, '1733', '7', '6', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Свитинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Свитинці', '49.570926153276545', '29.031020091998066', '1', 'AGAD 1/354/0/25/4239', NULL, NULL, NULL, NULL, NULL, NULL, '1733', '7', '6', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Соснівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Соснівка', '49.57634082997374', '29.003083847032766', '1', 'AGAD 1/354/0/25/4239', NULL, NULL, NULL, NULL, NULL, NULL, '1733', '7', '6', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Місто', 'Ширмівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ширмівка', '49.56122492595613', '29.09840937926036', '1', 'AGAD 1/354/0/25/4240', NULL, NULL, NULL, NULL, NULL, NULL, '1735', '9', '4', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Ліщинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ліщинці', '49.56599569863322', '29.174227233627267', '1', 'AGAD 1/354/0/25/4240', NULL, NULL, NULL, NULL, NULL, NULL, '1735', '9', '6', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Свитинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Свитинці', '49.570926153276545', '29.031020091998066', '1', 'AGAD 1/354/0/25/4240', NULL, NULL, NULL, NULL, NULL, NULL, '1735', '9', '7', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Соснівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Соснівка', '49.57634082997374', '29.003083847032766', '1', 'AGAD 1/354/0/25/4240', NULL, NULL, NULL, NULL, NULL, NULL, '1735', '9', '7', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Ширмівський ключ', 'Село', 'Смаржинці', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Смаржинці', '49.535510565016175', '29.145801900755792', '1', 'AGAD 1/354/0/25/4240', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9', '7', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, NULL, 'Село', 'Ширмівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ширмівка', '49.56122492595613', '29.09840937926036', '1', 'AGAD 1/354/0/25/4241', NULL, NULL, NULL, NULL, NULL, NULL, '1742', '7', '4', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, NULL, 'Село', 'Ширмівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ширмівка', '49.56122492595613', '29.09840937926036', '1', 'AGAD 1/354/0/25/4242', NULL, NULL, NULL, NULL, NULL, '1701-1800', NULL, '8', '5', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, NULL, 'Містечко', 'Погребище', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Місто', 'Погребище', '49.48633583201859', '29.26793992097412', '1', 'AGAD 1/354/0/25/3187', NULL, NULL, NULL, NULL, NULL, NULL, '1774', '25', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Містечко', 'Білилівка', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Білилівка', '49.68362439927635', '29.02618383713896', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Сокілець', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Сокілець', '49.685151799560025', '28.878038395840576', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Сошанськ', 'Вінницька обл.', 'Хмільницький р-н', 'Самгородоцька ОТГ', 'Село', 'Сошанське', '49.56092207942578', '28.90074443687155', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Зозулинці', 'Вінницька обл.', 'Хмільницький р-н', 'Самгородоцька ОТГ', 'Село', 'Зозулинці', '49.57092366998097', '28.92540840825562', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Махаринці', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Махаринці', '49.70889414130269', '28.9141023773746', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, 'Можливо мова про "Дубові Махаринці" (зараз "Дубові Махаринці") а не "Волоські Махаринці" (зараз "Махаринці")', 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Журбинці', 'Вінницька обл.', 'Хмільницький р-н', 'Самгородоцька ОТГ', 'Село', 'Журбинці', '49.65469805539245', '28.95297610927408', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Немиринці', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Немиринці', '49.621880123161894', '29.062720941297755', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Княжики', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Княжики', '49.621363511529644', '29.086062019394117', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Огіївка', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Огіївка', '49.63755044307666', '29.145076146349716', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Зарудинці', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Зарудинці', '49.651202738050756', '29.190147754973598', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Голубівка', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Голубівка', '49.6797910784493', '29.161902176432555', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Дерганівка', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Дерганівка', '49.68980906656524', '29.062062943585435', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Чарівка (Татарське селище)', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Селище', '49.836213521790086', '28.916998317810112', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Чернявка', 'Житомирська обл.', 'Бердичівський р-н', 'Вчорайшенська ОТГ', 'Село', 'Мала Чернявка', '49.8046647275943', '29.032009297463183', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', NULL, NULL, 'Село', 'Сестринівка', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Сестринівка', '49.73632891542403', '28.93735310346055', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.119', 'ЦДІАК', 'КМФ-15', '3', '119', NULL, NULL, NULL, '170', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', 'Білилівський ключ', 'Село', 'Немиринці', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Немиринці', '49.621880123161894', '29.062720941297755', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.126', 'ЦДІАК', 'КМФ-15', '3', '126', NULL, '1752-1790', NULL, NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', 'Білилівський ключ', 'Село', 'Махаринці Волоські', 'Вінницька обл.', 'Хмільницький р-н', 'Козятинська ОТГ', 'Село', 'Махаринці', '49.70889414130269', '28.9141023773746', '1', NULL, 'ЦДІАК', 'КМФ-15', '3', '126', NULL, '1752-1790', NULL, NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', 'Білилівський ключ', 'Село', 'Журбинці', 'Вінницька обл.', 'Хмільницький р-н', 'Самгородоцька ОТГ', 'Село', 'Журбинці', '49.65469805539245', '28.95297610927408', '1', NULL, 'ЦДІАК', 'КМФ-15', '3', '126', NULL, '1752-1790', NULL, NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', 'Білилівський ключ', 'Село', 'Княжики', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Княжики', '49.621363511529644', '29.086062019394117', '1', NULL, 'ЦДІАК', 'КМФ-15', '3', '126', NULL, '1752-1790', NULL, NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', 'Білилівський ключ', 'Село', 'Огіївка', 'Житомирська обл.', 'Бердичівський р-н', 'Ружинська ОТГ', 'Село', 'Огіївка', '49.63755044307666', '29.145076146349716', '1', NULL, 'ЦДІАК', 'КМФ-15', '3', '126', NULL, '1752-1790', NULL, NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Брацлавське воєводство', 'Брацлавський повіт', NULL, 'Село', 'Журбинці', 'Вінницька обл.', 'Хмільницький р-н', 'Самгородоцька ОТГ', 'Село', 'Журбинці', '49.65469805539245', '28.95297610927408', '1', 'ЦДІАК Ф.КМФ-15 О.3 С.162', 'ЦДІАК', 'КМФ-15', '3', '162', NULL, NULL, '1782', NULL, NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, NULL, 'Містечко', 'Білопілля', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Білопілля', '49.844930337728755', '28.869368844803198', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.67', 'ЦДІАК', 'КМФ-33', '1', '67', NULL, NULL, NULL, '10', '3', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, NULL, 'село', 'Непедівка', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Непедівка', '49.777770573728986', '28.804141886218044', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.67', 'ЦДІАК', 'КМФ-33', '1', '67', NULL, '1742', NULL, '10', '8', NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'село', 'Пузирки', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Пузирки', '49.826985787274275', '28.77131576745218', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.117', 'ЦДІАК', 'КМФ-33', '1', '117', NULL, '1650-1759', NULL, '101', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Містечко', 'Білопілля', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Білопілля', '49.844930337728755', '28.869368844803198', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1742', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Гурівці', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Гурівці', '49.79974753685763', '28.76960202128837', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1740', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Непедівка', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Непедівка', '49.777770573728986', '28.804141886218044', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1742', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Красівка', 'Житомирська обл.', 'Бердичівський р-н', 'Семенівська ОТГ', 'Село', 'Красівка', '49.904067748569425', '28.832108090616817', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1751', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Пузирки', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Пузирки', '49.826985787274275', '28.77131576745218', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, NULL, '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Вернигородок', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Вернигородок', '49.783205170902995', '28.891532028827257', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1758', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Верболози', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Верболози', '49.799883454351885', '28.85659940295974', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, NULL, '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Панасівка', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Панасівка', '49.837930369300885', '28.802260970137056', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, '1759', '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Держанівка', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Держанівка', '49.812013035441915', '28.816480653048163', '1', 'ЦДІАК Ф.КМФ-33 О.1 С.119', 'ЦДІАК', 'КМФ-33', '1', '119', NULL, NULL, NULL, '140', NULL, NULL, NULL, NULL, 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воводство', NULL, 'Білопільський ключ', 'Село', 'Пузирки', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Пузирки', '49.826985787274275', '28.77131576745218', '1', 'LT LVIA Ф.716 О.4 С.72', NULL, NULL, NULL, NULL, NULL, '1650, 
1742-1756', NULL, '69', NULL, NULL, NULL, 'У справі є інші документи окрім інвентаря', 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', NULL, 'Білопільський ключ', 'Місто', 'Білопілля', 'Вінницька обл.', 'Хмільницький р-н', 'Глуховецька ОТГ', 'Село', 'Білопілля', '49.844930337728755', '28.869368844803198', '1', 'LT LVIA Ф.716 О.4 С.74', NULL, NULL, NULL, NULL, NULL, '1693 - 1778', NULL, '82', NULL, NULL, NULL, 'У справі є інші документи окрім інвентаря', 'c22440cc-0fe5-418d-be17-7cd07a74893c');
INSERT INTO records (old_province, old_district, old_community, old_settlement_type, old_settlement_name, current_region, current_district, current_community, current_settlement_type, current_settlement_name, latitude, longitude, mark_type, case_signature, archive, fonds, series

, record, additional_case_signature, case_date, inventory_year, pages_count, inventory_start_page, scans_url, case_title, notes, created_by) VALUES ('Київське воєводство', NULL, 'Ширмівський ключ', 'Місто', 'Ширмівка', 'Вінницька обл.', 'Вінницький й р-н', 'Погребищенська ОТГ', 'Село', 'Ширмівка', '49.56122492595613', '29.09840937926036', '1', 'LT LVIA Ф.459 О.1 С.2430', NULL, NULL, NULL, NULL, NULL, '1727-1743', NULL, NULL, NULL, NULL, NULL, 'У справі є інші документи окрім інвентаря', 'c22440cc-0fe5-418d-be17-7cd07a74893c');
